name: Docker Image

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  docker-image:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: "${{ fromJson(inputs.plan).releases[0].app_version }}"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: artifacts-build-local-x86_64-unknown-linux-gnu
          path: artifacts

      - run: |
          tar -xvf artifacts/derp-client-verifier-x86_64-unknown-linux-gnu.tar.xz
          cp derp-client-verifier-x86_64-unknown-linux-gnu/derp-client-verifier .
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: dist.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/derp-client-verifier:${{ env.APP_VERSION }}
            ghcr.io/${{ github.actor }}/derp-client-verifier:latest
            ${{ github.actor }}/derp-client-verifier:${{ env.APP_VERSION }}
            ${{ github.actor }}/derp-client-verifier:latest
